package entidades;
// Generated 25/02/2014 20:18:16 by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Lista generated by hbm2java
 */
public class Lista  implements java.io.Serializable {


     private int idlista;
     private Usuario usuario;
     private String delista;
     private Date dtlista;

    public Lista() {
    }

	
   
    public Lista(int idlista, Usuario usuario, String delista, Date dtlista) {
       this.idlista = idlista;
       this.usuario = usuario;
       this.delista = delista;
       this.dtlista = dtlista;
    }
   
    public int getIdlista() {
        return this.idlista;
    }
    
    public void setIdlista(int idlista) {
        this.idlista = idlista;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getDelista() {
        return this.delista;
    }
    
    public void setDelista(String delista) {
        this.delista = delista;
    }
    public Date getDtlista() {
        return this.dtlista;
    }
    
    public void setDtlista(Date dtlista) {
        this.dtlista = dtlista;
    }




}


