package entidades;
// Generated 25/02/2014 20:18:16 by Hibernate Tools 3.6.0



/**
 * ListaIt generated by hbm2java
 */
public class ListaIt  implements java.io.Serializable {


     private ListaItId id;
     private Produto produto;
     private Character idstatus;

    public ListaIt() {
    }

	
    public ListaIt(ListaItId id) {
        this.id = id;
    }
    public ListaIt(ListaItId id, Produto produto, Character idstatus) {
       this.id = id;
       this.produto = produto;
       this.idstatus = idstatus;
    }
   
    public ListaItId getId() {
        return this.id;
    }
    
    public void setId(ListaItId id) {
        this.id = id;
    }
    public Produto getProduto() {
        return this.produto;
    }
    
    public void setProduto(Produto produto) {
        this.produto = produto;
    }
    public Character getIdstatus() {
        return this.idstatus;
    }
    
    public void setIdstatus(Character idstatus) {
        this.idstatus = idstatus;
    }




}


