package entidades;
// Generated 25/02/2014 20:18:16 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private int idusuario;
     private String nmusuario;
     private Set<Lista> listas = new HashSet<Lista>(0);

    public Usuario() {
    }

	
    public Usuario(int idusuario, String nmusuario) {
        this.idusuario = idusuario;
        this.nmusuario = nmusuario;
    }
    public Usuario(int idusuario, String nmusuario, Set<Lista> listas) {
       this.idusuario = idusuario;
       this.nmusuario = nmusuario;
       this.listas = listas;
    }
   
    public int getIdusuario() {
        return this.idusuario;
    }
    
    public void setIdusuario(int idusuario) {
        this.idusuario = idusuario;
    }
    public String getNmusuario() {
        return this.nmusuario;
    }
    
    public void setNmusuario(String nmusuario) {
        this.nmusuario = nmusuario;
    }
    public Set<Lista> getListas() {
        return this.listas;
    }
    
    public void setListas(Set<Lista> listas) {
        this.listas = listas;
    }




}


